#!/bin/sh

pushd . > /dev/null
cd `dirname $0`
FILEROOT=$PWD
popd > /dev/null

linkfile () {
    cp -R ~/$1 $FILEROOT/.bak/$1 > /dev/null
    ln -sf $FILEROOT/$1 ~/$1
}

mkdir -p $FILEROOT/.bak/

linkfile '.bashrc'
linkfile '.emacs'
linkfile '.emacs.d'
linkfile '.profile'
linkfile '.bash_profile'
linkfile '.gitignore'
linkfile '.gitconfig'
linkfile '.inputrc'
linkfile 'lib'
linkfile '.screenrc'
linkfile '.subversion'