#!/bin/sh

pushd . > /dev/null
cd `dirname $0`
FILEROOT=$PWD
popd > /dev/null

linkfile () {
    cp -R ~/$1 $FILEROOT/.bak/$1 > /dev/null
    rm -Rf ~/$1
    ln -sf $FILEROOT/$1 ~/$1
}

mkdir -p $FILEROOT/.bak/

for file in $(find -E $FILEROOT -depth 1 -not -regex '.*(setup|\.git|~|#|.bak|init)$'); do
    linkfile `basename $file`
done
